name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"
  release:
    types:
      - published
  workflow_dispatch:

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      cache: true
      cache-mode: max
      cache-scope: mimotion
      set-meta-labels: true
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=ref,event=branch
        type=ref,event=tag
        type=raw,value=${{ github.event.release.tag_name }},enable=${{ github.event_name == 'release' }}
        type=semver,pattern={{version}},value=${{ github.event.release.tag_name || github.ref_name }}
        type=semver,pattern={{major}}.{{minor}},value=${{ github.event.release.tag_name || github.ref_name }}
        type=sha,prefix=
        type=raw,value=latest,enable={{is_default_branch}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
